name: Lint github-action

on: [  'pull_request' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: docker://rhysd/actionlint:1.6.26
        with:
          args: -color
